# Generated by Django 3.2.8 on 2021-11-28 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(default='', max_length=50)),
                ('tipo_de_consulta', models.CharField(default='', max_length=50)),
                ('data_nascimento', models.CharField(default='', max_length=12)),
                ('genero', models.CharField(max_length=50)),
                ('horario_agendado', models.CharField(default='', max_length=50)),
                ('forma_de_pagamento', models.CharField(default='', max_length=50)),
                ('cpf', models.CharField(default='', max_length=50)),
                ('nome_completo', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('celular', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Agendar_consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_da_consulta_marcada', models.DateTimeField()),
                ('data_criado_agendamento', models.DateTimeField(auto_now=True)),
                ('is_payment', models.BooleanField(default=False)),
                ('medico_e_especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_da_consulta_marcada'],
            },
        ),
    ]
